# Front view pinhole projection
$(arg camera_name)_pinhole_front:
  update_rate: 1
  always_recompute_mapping: false
  base_frame: head_camera
  pose: [0, 0, 0, 0, 0, 3.14]
  virtual_sensor_frame: pinhole_front_camera_frame
  virtual_sensor_optical_frame: pinhole_front_optical_frame
  projection_type: image_projection_plugins::PinholeProjection
  projection_parameters:
    image_width: 640
    image_height: 480
    horizontal_fov: 90
    focal_length: 0.1

# Mercator projection
$(arg camera_name)_mercator_projection:
  update_rate: 10
  base_frame: head_camera
  pose: [0, 0, 0, 0, 0, 0]
  projection_type: image_projection_plugins::MercatorProjection
  projection_parameters:
    image_width: 1100
    image_height: 500
    cylinder_radius: 10000
  
# Ideal fisheye
$(arg camera_name)_fisheye:
  update_rate: 1
  always_recompute_mapping: false
  base_frame: head_camera
  pose: [0, 0, 0, 0, 0, 1.57]
  virtual_sensor_frame: camera360_ideal_fisheye_link
  virtual_sensor_optical_frame: camera360_ideal_fisheye_optical_frame
  projection_type: image_projection_plugins::IdealFisheyeProjection
  projection_parameters:
    image_width: &fisheye_resolution 512
    image_height: *fisheye_resolution
    fov: &fisheye_fov 200
    sphere_radius: &fisheye_sphere_radius 0.1
